[project]
name = "kkbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "rich>=14.2.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
